.\" afetch
.TH "AFETCH" "1" "19 October 2020" "afetch configuration manual"
.SH NAME
afetch - another fetch
.SH DESCRIPTION
afetch is a small, fast system information program. It can be configured at compile time by editing the config.h file.
.SH LOWERCASE
Defining LOWERCASE to 1 will force all text to be lowercase, but there is currently an unknown error causing the program to segfault on some distros when this is enabled. Set to 0 to enable, and 1 to disable
.SH SHELLPATH
Defining SHELLPATH to 1 will disable this, so only the shell name will be displayed. If set to 0, it's enabled and will show the full file path to the shell (eg /bin/bash)
.SH BLOCKS
If set to 0, coloured blocks will be printed on screen below the logo. Set to 1 to disable.
.SH *TEXT
This is the string that is printed out before the information is displayed. (eg If 'SHELLTEXT is set to 'MYSHELL', then the program will output 'MYSHELL /bin/bash')
.SH TEXTCOLOUR
The colour of the text that displays the information.
.SH CUSTOM COLOURS
If the value 'OVERRIDECOLOUR' is uncommented, then the program will use a custom colour defined in CUSTOMCOLOUR. See a list of available colours in the 'COLOURS' file. 
.SH CUSTOMART
If set to 1, a custom logo is disabled and if set to 0, then it's enabled. The logo can be defined by editing the values COL*, where COL1 is the first line of the art, COL2 is the second and so on. The maximum number of lines is 8
.SH REQUESTS
Only some distributions are supported, but you can request support for your distro by opening an issue on github (https://github.com/13-CF/afetch) and providing the contents of your /etc/os-release file.
